// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Request
	Response
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Verb int32

const (
	Verb_GET        Verb = 1
	Verb_SET        Verb = 2
	Verb_DEL        Verb = 4
	Verb_CREATE     Verb = 256
	Verb_PERSISTENT Verb = 512
	Verb_EPHEMERAL  Verb = 1024
	Verb_SEQUENTIAL Verb = 2048
	Verb_NUMBER     Verb = 8192
	Verb_DIR        Verb = 4096
	Verb_WATCH      Verb = 65536
	Verb_WATCH_ALL  Verb = 131072
	Verb_WATCH_PUSH Verb = 262144
	Verb_SERVER     Verb = 268435456
	Verb_NONE       Verb = 268435457
)

var Verb_name = map[int32]string{
	1:         "GET",
	2:         "SET",
	4:         "DEL",
	256:       "CREATE",
	512:       "PERSISTENT",
	1024:      "EPHEMERAL",
	2048:      "SEQUENTIAL",
	8192:      "NUMBER",
	4096:      "DIR",
	65536:     "WATCH",
	131072:    "WATCH_ALL",
	262144:    "WATCH_PUSH",
	268435456: "SERVER",
	268435457: "NONE",
}
var Verb_value = map[string]int32{
	"GET":        1,
	"SET":        2,
	"DEL":        4,
	"CREATE":     256,
	"PERSISTENT": 512,
	"EPHEMERAL":  1024,
	"SEQUENTIAL": 2048,
	"NUMBER":     8192,
	"DIR":        4096,
	"WATCH":      65536,
	"WATCH_ALL":  131072,
	"WATCH_PUSH": 262144,
	"SERVER":     268435456,
	"NONE":       268435457,
}

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}
func (x Verb) String() string {
	return proto.EnumName(Verb_name, int32(x))
}
func (x *Verb) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Verb_value, data, "Verb")
	if err != nil {
		return err
	}
	*x = Verb(value)
	return nil
}

type Err int32

const (
	// don't use value 0
	Err_OK                        Err = 0
	Err_UNKNOWN_VERB              Err = 2
	Err_READ_ONLY                 Err = 3
	Err_TIME_OUT                  Err = 4
	Err_BAD_PATH                  Err = 6
	Err_NOT_LEADER                Err = 7
	Err_NOT_DIR                   Err = 20
	Err_IS_DIR                    Err = 21
	Err_BAD_PATH_PAT              Err = 22
	Err_UNKNOWN                   Err = 23
	Err_DATA_MUST_BE_NUMBER       Err = 24
	Err_ONE_ITEM_OF_DIR_IS_FILE   Err = 26
	Err_LAST_FILE_IS_DIR_ALREADY  Err = 27
	Err_FILE_ATTR_NOT_IS_INCREASE Err = 28
	Err_DIR_CANT_REMOVE           Err = 29
	Err_JSON_MARSHAL              Err = 30
	Err_ROOT_IS_READONLY          Err = 31
	Err_PATH_FILE_ATTR            Err = 32
	Err_UNSIGNINT_ERR             Err = 34
	Err_RET_LESS_OF_ZERO          Err = 35
	Err_EXIST                     Err = 1033
	Err_NOT_EXIST                 Err = 1025
	Err_OTHER                     Err = 127
	Err_ERR                       Err = 128
	Err_PROTO_MARSHAL             Err = 129
)

var Err_name = map[int32]string{
	0:    "OK",
	2:    "UNKNOWN_VERB",
	3:    "READ_ONLY",
	4:    "TIME_OUT",
	6:    "BAD_PATH",
	7:    "NOT_LEADER",
	20:   "NOT_DIR",
	21:   "IS_DIR",
	22:   "BAD_PATH_PAT",
	23:   "UNKNOWN",
	24:   "DATA_MUST_BE_NUMBER",
	26:   "ONE_ITEM_OF_DIR_IS_FILE",
	27:   "LAST_FILE_IS_DIR_ALREADY",
	28:   "FILE_ATTR_NOT_IS_INCREASE",
	29:   "DIR_CANT_REMOVE",
	30:   "JSON_MARSHAL",
	31:   "ROOT_IS_READONLY",
	32:   "PATH_FILE_ATTR",
	34:   "UNSIGNINT_ERR",
	35:   "RET_LESS_OF_ZERO",
	1033: "EXIST",
	1025: "NOT_EXIST",
	127:  "OTHER",
	128:  "ERR",
	129:  "PROTO_MARSHAL",
}
var Err_value = map[string]int32{
	"OK":                        0,
	"UNKNOWN_VERB":              2,
	"READ_ONLY":                 3,
	"TIME_OUT":                  4,
	"BAD_PATH":                  6,
	"NOT_LEADER":                7,
	"NOT_DIR":                   20,
	"IS_DIR":                    21,
	"BAD_PATH_PAT":              22,
	"UNKNOWN":                   23,
	"DATA_MUST_BE_NUMBER":       24,
	"ONE_ITEM_OF_DIR_IS_FILE":   26,
	"LAST_FILE_IS_DIR_ALREADY":  27,
	"FILE_ATTR_NOT_IS_INCREASE": 28,
	"DIR_CANT_REMOVE":           29,
	"JSON_MARSHAL":              30,
	"ROOT_IS_READONLY":          31,
	"PATH_FILE_ATTR":            32,
	"UNSIGNINT_ERR":             34,
	"RET_LESS_OF_ZERO":          35,
	"EXIST":                     1033,
	"NOT_EXIST":                 1025,
	"OTHER":                     127,
	"ERR":                       128,
	"PROTO_MARSHAL":             129,
}

func (x Err) Enum() *Err {
	p := new(Err)
	*p = x
	return p
}
func (x Err) String() string {
	return proto.EnumName(Err_name, int32(x))
}
func (x *Err) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Err_value, data, "Err")
	if err != nil {
		return err
	}
	*x = Err(value)
	return nil
}

type Request struct {
	Tag              *string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Verb             *uint32 `protobuf:"varint,2,opt,name=verb" json:"verb,omitempty"`
	Path             *string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Value            *string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

func (m *Request) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Request) GetVerb() uint32 {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return 0
}

func (m *Request) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Request) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

// see doc/proto.md
type Response struct {
	Tag              *string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	Verb             *uint32 `protobuf:"varint,2,opt,name=verb" json:"verb,omitempty"`
	Path             *string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Value            *string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	Cnt              *string `protobuf:"bytes,5,opt,name=cnt" json:"cnt,omitempty"`
	ErrCode          *Err    `protobuf:"varint,100,opt,name=errCode,enum=protobuf.Err" json:"errCode,omitempty"`
	ErrDes           *string `protobuf:"bytes,101,opt,name=errDes" json:"errDes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetTag() string {
	if m != nil && m.Tag != nil {
		return *m.Tag
	}
	return ""
}

func (m *Response) GetVerb() uint32 {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return 0
}

func (m *Response) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Response) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *Response) GetCnt() string {
	if m != nil && m.Cnt != nil {
		return *m.Cnt
	}
	return ""
}

func (m *Response) GetErrCode() Err {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return Err_OK
}

func (m *Response) GetErrDes() string {
	if m != nil && m.ErrDes != nil {
		return *m.ErrDes
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf.Verb", Verb_name, Verb_value)
	proto.RegisterEnum("protobuf.Err", Err_name, Err_value)
}
